### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by llyyccccc** [Traffic-X/ViT-CoMer#25]
26 errors detected in the compilation of "F:/ViT-CoMer-main/segmentation/ops/src/cuda/ms_deform_attn_cuda.cu".
ms_deform_attn_cuda.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\anaconda3\envs\VITC\lib\site-packages\torch\utils\cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "D:\anaconda3\envs\VITC\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    setup(
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
    return run_commands(dist)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
    dist.run_commands()
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\dist.py", line 950, in run_command
    super().run_command(command)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\install.py", line 97, in run
    self.do_egg_install()
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\install.py", line 149, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\dist.py", line 950, in run_command
    super().run_command(command)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\bdist_egg.py", line 168, in run
    cmd = self.call_command('install_lib', warn_dir=False)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\bdist_egg.py", line 154, in call_command
    self.run_command(cmdname)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\dist.py", line 950, in run_command
    super().run_command(command)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\install_lib.py", line 19, in run
    self.build()
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\dist.py", line 950, in run_command
    super().run_command(command)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\build_ext.py", line 98, in run
    _build_ext.run(self)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
    self.build_extensions()
  File "D:\anaconda3\envs\VITC\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\build_ext.py", line 263, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 557, in build_extension
    objects = self.compiler.compile(
  File "D:\anaconda3\envs\VITC\lib\site-packages\torch\utils\cpp_extension.py", line 682, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\anaconda3\envs\VITC\lib\site-packages\torch\utils\cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\anaconda3\envs\VITC\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by yaosx425** [comment]
> 26 errors detected in the compilation of "F:/ViT-CoMer-main/segmentation/ops/src/cuda/ms_deform_attn_cuda.cu". ms_deform_attn_cuda.cu ninja: build stopped: subcommand failed. Traceback (most recent call last): File "D:\anaconda3\envs\VITC\lib\site-packages\torch\utils\cpp_extension.py", line 1666, in _run_ninja_build subprocess.run( File "D:\anaconda3\envs\VITC\lib\subprocess.py", line 516, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "setup.py", line 59, in setup( File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools__init__.py", line 117, in setup return distutils.core.setup(**attrs) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\core.py", line 183, in setup return run_commands(dist) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\core.py", line 199, in run_commands dist.run_commands() File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\dist.py", line 954, in run_commands self.run_command(cmd) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\dist.py", line 950, in run_command super().run_command(command) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\dist.py", line 973, in run_command cmd_obj.run() File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\install.py", line 97, in run self.do_egg_install() File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\install.py", line 149, in do_egg_install self.run_command('bdist_egg') File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\cmd.py", line 316, in run_command self.distribution.run_command(command) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\dist.py", line 950, in run_command super().run_command(command) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\dist.py", line 973, in run_command cmd_obj.run() File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\bdist_egg.py", line 168, in run cmd = self.call_command('install_lib', warn_dir=False) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\bdist_egg.py", line 154, in call_command self.run_command(cmdname) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\cmd.py", line 316, in run_command self.distribution.run_command(command) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\dist.py", line 950, in run_command super().run_command(command) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\dist.py", line 973, in run_command cmd_obj.run() File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\install_lib.py", line 19, in run self.build() File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\command\install_lib.py", line 110, in build self.run_command('build_ext') File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\cmd.py", line 316, in run_command self.distribution.run_command(command) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\dist.py", line 950, in run_command super().run_command(command) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\dist.py", line 973, in run_command cmd_obj.run() File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\build_ext.py", line 98, in run _build_ext.run(self) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\command\build_ext.py", line 359, in run self.build_extensions() File "D:\anaconda3\envs\VITC\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions build_ext.build_extensions(self) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\command\build_ext.py", line 476, in build_extensions self._build_extensions_serial() File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\command\build_ext.py", line 502, in _build_extensions_serial self.build_extension(ext) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools\command\build_ext.py", line 263, in build_extension _build_ext.build_extension(self, ext) File "D:\anaconda3\envs\VITC\lib\site-packages\setuptools_distutils\command\build_ext.py", line 557, in build_extension objects = self.compiler.compile( File "D:\anaconda3\envs\VITC\lib\site-packages\torch\utils\cpp_extension.py", line 682, in win_wrap_ninja_compile _write_ninja_file_and_compile_objects( File "D:\anaconda3\envs\VITC\lib\site-packages\torch\utils\cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects _run_ninja_build( File "D:\anaconda3\envs\VITC\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error compiling objects for extension

请问您解决了吗？
